<?php

require_once dirname(dirname(dirname(__FILE__))) . '/AiryUnitTest.php';

/**
 * Test class for AclUtility.
 * Generated by PHPUnit on 2012-05-02 at 15:35:44.
 */
class AclUtilityTest extends AiryUnitTest {

    /**
     * @var AclUtility
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function testSetUp() {
        $this->object = new AclUtility();
        $aclxml = dirname(dirname((dirname(__FILE__)))) . '/testfiles/test_aclxml.xml';
        $this->object->setAclXml($aclxml);
    }


    /**
     * @covers AclUtility::getAuthentications
     * @todo Implement testGetAuthentications().
     */
    public function testGetAuthentications() {
		$auth = $this->object->getAuthentications();
		$arr = $auth['test_module2'];
		
		$this->assertEquals('UserLogin', $arr['controller']);
		$this->assertEquals('signIn', $arr['sign_in_action']);
		$this->assertEquals('userLogin', $arr['login_action']);
		$this->assertEquals('userLoginError', $arr['login_error_action']);
		$this->assertEquals('loginout', $arr['logout_action']);
		
		$exclusiveActions = $arr['other_exclusive_actions'];
		$this->assertEquals('register', $exclusiveActions[0]);
		$this->assertEquals('add', $exclusiveActions[1]);
		$this->assertEquals('sendemail', $exclusiveActions[2]);
		
    }

    /**
     * @covers AclUtility::getSuccessfulDispatch
     * @todo Implement testGetSuccessfulDispatch().
     */
    public function testGetSuccessfulDispatch() {
    	$auth = $this->object->getSuccessfulDispatch();
		$arr = $auth['test_module1'];
		
		$this->assertEquals('Admin', $arr['controller']);
		$this->assertEquals('getAdm', $arr['action']);

    }



//    /**
//     * @covers AclUtility::getAllMapTblAttr
//     * @todo Implement testGetAllMapTblAttr().
//     */
//    public function testGetAllMapTblAttr() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

//    /**
//     * @covers AclUtility::getTableById
//     * @todo Implement testGetTableById().
//     */
//    public function testGetTableById() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

//    /**
//     * @covers AclUtility::getMapTables
//     * @todo Implement testGetMapTables().
//     */
//    public function testGetMapTables() {
//    	$auth = $this->object->getMapTables();
//
//    	$this->assertEquals('account', $auth[1]);
//		$this->assertEquals('member', $auth[2]);
//    }

//    /**
//     * @covers AclUtility::getMappingModuleTables
//     * @todo Implement testGetMappingModuleTables().
//     */
//    public function testGetMappingModuleTables() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

//    /**
//     * @covers AclUtility::getTableIdByModule
//     * @todo Implement testGetTableIdByModule().
//     */
//    public function testGetTableIdByModule() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers AclUtility::getMappingFieldByTbl
     * @todo Implement testGetMappingFieldByTbl().
     */
    public function testGetMappingFieldByTbl() {
    	$arr = $this->object->getMappingFieldByTbl(1);
    	
    	$this->assertEquals('account_id', $arr['user_id']);
    	$this->assertEquals('pwd', $arr['pwd']);
    	$this->assertEquals('salt', $arr['pwd_encrypt']);
    	$this->assertEquals('is_delete', $arr['is_delete']);
    	$this->assertEquals('0', $arr['is_delete_value']);
    }

//    /**
//     * @covers AclUtility::getRoleTypesByTbl
//     * @todo Implement testGetRoleTypesByTbl().
//     */
//    public function testGetRoleTypesByTbl() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AclUtility::getLoginedAccessRules
//     * @todo Implement testGetLoginedAccessRules().
//     */
//    public function testGetLoginedAccessRules() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers AclUtility::getBrowseRules
     * @todo Implement testGetBrowseRules().
     */
    public function testGetBrowseRules() {
		$arr = $this->object->getBrowseRules();
		
		$this->assertEquals('add', $arr['test_module1']['Admin'][0]);
		$this->assertEquals('getTitle', $arr['test_module1']['Admin'][1]);
		$this->assertEquals('ALL_ACTIONS', $arr['test_module1']['Event']);
    }

}

?>
